name: Build Jekyll + Auto-generate Index
env:
  GH_TOKEN: ${{ secrets.PAT_TOKEN }}

on:
  push:
    branches: ["main"]
    #paths:
    #  - "notes/**"
  workflow_dispatch:

permissions:
  contents: write   # 需要 write 權限 commit 回 repo
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Ruby + Bundler (Jekyll)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          bundler: '2.4.22'

      # 3️⃣ Install Jekyll dependencies
      - name: Install Jekyll dependencies
        run: bundle install

      # 4️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 5️⃣ Install Python dependencies
      - name: Install Python dependencies
        run: pip install PyGithub jinja2

      # 6️⃣ Generate index.html in repo root
      - name: Generate index.html
        run: python scripts/generate_index.py

      # 7️⃣ Commit generated index.html back to repo only if changed
      - name: Commit index.html if changed
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add index.html
          if ! git diff --cached --quiet; then
            git commit -m "Auto-generate index.html"
            git push https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            echo "✅ index.html committed and pushed."
          else
            echo "ℹ️ No changes in index.html. Nothing to commit."
          fi

      # 8️⃣ Build Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build --destination ./_site

      # 9️⃣ Upload Pages artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      # 🔟 Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
